apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: 3-25-app 
  janus-idp.io/tekton: 3-25-app
  backstage.io/kubernetes-id: 3-25-app
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: 3-25-app
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  