apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: 3-25-app-gitops
  description: This is GitOps manifest for 3-25-app   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: 3-25-app
    janus-idp.io/tekton: 3-25-app 
    backstage.io/kubernetes-id: 3-25-app 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:3-25-app
